name: "Tests: Unit cac"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key:
            # prettier-ignore
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 6.0.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm run test:ci
        working-directory: ./apps/cac
      - name: Vercel Pull
        # prettier-ignore
        run: npx vercel pull --token ${{ secrets.ACTIONS_DEPLOY_TO_VERCEL }} --yes
      - name: Vercel Build
        run: npx vercel build
      - name: Deploy to Vercel
        if: ${{ success() }}
        run: |
          npx vercel --token ${{ secrets.ACTIONS_DEPLOY_TO_VERCEL }} --prebuilt --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_CAC }}
